config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :films
  resources :comments, only: :create
  resources :ratings, only: :create

  root to: 'films#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :film
  belongs_to :user
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :comments
  has_many :ratings

  validates :title, presence: true
  validates :rating, presence: true
  validates :year, presence: true
  validates :genre, presence: true
  validates :company, presence: true
  validates :producer, presence: true
  validates :actors, presence: true
  validates :cost, presence: true
  validates :image_link, presence: true, format: { with: /\A(http|https):\/\/\S+\/\S+.jpg\z/ }

  def self.search(keywords)
    if keywords
      where(
        "title LIKE ? OR year = ? OR actors LIKE ? OR producer LIKE ? OR company LIKE ? OR genre LIKE ?",
        "%#{keywords}%",
        keywords.to_i,
        "%#{keywords}%",
        "%#{keywords}%",
        "%#{keywords}%",
        "%#{keywords}%"
      ).order('id DESC')
    else
      order('id DESC')
    end
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :film

  validates :value, presence: true, format: { with: /\A\d.?\d{0,3}\z/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    film = Film.find(@comment.film_id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to film, notice: "Ваш комментарий был успешно добавлен." }
        format.json { render json: @comment.id, status: :created }
      else
        format.html { redirect_to film, notice: @comment.errors }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text, :user_id, :film_id)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]

  def index
    if params[:search]
      @films = Film.search(params[:search]).sort_by(&:rating).reverse
    else
      @films = Film.all.sort_by(&:rating).reverse
    end

    if params[:sort]
      @films = @films.sort_by(&:year) if params[:sort] == 'by_year'
      @films = @films.sort_by(&:genre) if params[:sort] == 'by_genre'
      @films = @films.sort_by(&:company) if params[:sort] == 'by_company'
      @films = @films.sort_by(&:producer) if params[:sort] == 'by_producer'
      @films.reverse! if params[:desc] == '1'
    end
  end

  def show
    @comments = @film.comments
    @rating = @film.ratings.where(user_id: current_user.id).first&.value if current_user
  end

  def new
    @film = Film.new
  end

  def edit; end

  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: "Фильм был успешно создан." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: "Фильм был успешно обновлён." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: "Фильм был успешно удалён." }
      format.json { head :no_content }
    end
  end

  private
    def set_film
      @film = Film.find(params[:id])
    end

    def film_params
      params.require(:film).permit(:title, :year, :genre, :company, :producer, :actors, :cost, :image_link, :rating)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @rating = Rating.new(rating_params)
    film = Film.find(@rating.film_id)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to film, notice: "Ваш рейтинг был успешно добавлен." }
        format.json { render json: @rating.id, status: :created }
      else
        format.html { redirect_to film, notice: @rating.errors }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def rating_params
      params.permit(:value, :user_id, :film_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_films_table.html.erb
<thead>
  <tr>
      <th scope="col">Рейтинг</th>
      <th scope="col">Название</th>
      <th scope="col">Год выпуска</th>
      <th scope="col">Жанр</th>
      <th scope="col">Кинокомпания</th>
      <th scope="col">Режиссер</th>
      <th scope="col">Актеры</th>
      <th scope="col">Стоимость</th>
  </tr>
</thead>

<tbody>
  <% films.each do |film| %>
  <tr>
      <td><span class="badge bg-secondary"><%= film.rating %></span></td>
      <td><%= link_to film.title, film %></td>
      <td><%= film.year %></td>
      <td><%= film.genre %></td>
      <td><%= film.company %></td>
      <td><%= film.producer %></td>
      <td><%= film.actors %></td>
      <td><%= film.cost %></td>
  </tr>
  <% end %>
</tbody>

app/views/films/_form.html.erb
<div class="film-edit-container">
  <%= form_with(model: film, local: true) do |form| %>
    <% if film.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(film.errors.count, "error") %> prohibited this film from being saved:</h2>

        <ul>
        <% film.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mt-3">
      <%= form.label :title, 'Название', class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :year, 'Год выпуска', class: 'form-label' %>
      <%= form.number_field :year, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :genre, 'Жанр', class: 'form-label' %>
      <%= form.text_field :genre, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :company, 'Кинокомпания', class: 'form-label' %>
      <%= form.text_field :company, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :producer, 'Режиссер', class: 'form-label' %>
      <%= form.text_field :producer, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :actors, 'Актеры', class: 'form-label' %>
      <%= form.text_field :actors, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :cost, 'Стоимость', class: 'form-label' %>
      <%= form.text_field :cost, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :image_link, 'Ссылка на изображение постера', class: 'form-label' %>
      <%= form.text_field :image_link, class: 'form-control' %>
    </div>

    <div class="field mt-3">
      <%= form.label :rating, 'Рейтинг', class: 'form-label' %>
      <%= form.text_field :rating, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit 'Сохранить', class: 'btn btn-sm btn-primary mt-3' %>
    </div>
  <% end %>

</div>

app/views/films/edit.html.erb
<h5>Редактировать фильм</h5>

<%= render 'form', film: @film %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>

<div class="control-buttons">
  <% if current_user && current_user.admin? %>
    <%= link_to 'Добавить фильм', new_film_path, method: :get, class: 'btn btn-sm btn-warning add-film-btn' %>
  <% end %>
  <button
    class="btn btn-sm btn-info sort-btn right"
    data-bs-toggle="collapse"
    data-bs-target="#sorter"
    aria-expanded="false"
    aria-controls="sorter"
  >
    Сортировка
  </button>
  <button
    class="collapsed btn btn-sm btn-info filter-btn right"
    data-bs-toggle="collapse"
    data-bs-target="#filter"
    aria-expanded="false"
    aria-controls="filter"
  >
    Фильтр
  </button>
  <div id="filter" class="accordion-collapse collapse right" aria-labelledby="filter">
    <div class="accordion-body">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Фильтрация фильмов</h5>
          <%= form_with(url: films_path, method: :get) do |form| %>
            <div class="form-group">
              <%= form.label :search, 'Поиск' %>
              <%= form.text_field :search, class: 'form-control' %>
            </div>

            <div class="actions">
              <%= form.submit 'Применить', class: 'btn btn-sm btn-success' %>
              <%= link_to 'Сбросить', films_path, method: :get, class: 'btn btn-sm btn-danger', remote: true %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div id="sorter" class="accordion-collapse collapse right" aria-labelledby="sorter">
    <div class="accordion-body">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Сортировка фильмов</h5>
          <%= form_with(url: films_path, method: :get) do |form| %>
            <div class="form-group">
              <%= form.label :desc, 'В обратном порядке' %>
              <%= form.check_box :desc %>
            </div>

            <div class="form-group">
              <%= form.label :sort, 'По году выпуска', value: 'by_year' %>
              <%= form.radio_button :sort, 'by_year' %>
              <br />
              <%= form.label :sort, 'По жанру', value: 'by_genre' %>
              <%= form.radio_button :sort, 'by_genre' %>
              <br />
              <%= form.label :sort, 'По кинокомпании', value: 'by_company' %>
              <%= form.radio_button :sort, 'by_company' %>
              <br />
              <%= form.label :sort, 'По режиссеру', value: 'by_producer' %>
              <%= form.radio_button :sort, 'by_producer' %>
            </div>

            <div class="actions">
              <%= form.submit 'Применить', class: 'btn btn-sm btn-success' %>
              <%= link_to 'Сбросить', films_path, method: :get, class: 'btn btn-sm btn-danger', remote: true %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<table class="table film-table">
  <%= render partial: 'films_table', locals: {films: @films} %>
</table>

app/views/films/index.js.erb
$(".film-table").html("<%= j render(partial: 'films_table', locals: { films: @films }) %>");

app/views/films/new.html.erb
<h5>Добавить фильм</h5>

<%= render 'form', film: @film %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<div class="film-card">
  <img src=<%= @film.image_link %> class="poster-img" />

  <div class="film-info">
    <% if current_user && current_user.admin? %>
      <%= link_to 'Редактировать', edit_film_path(@film),
                  class: 'btn btn-sm btn-warning'
      %>

      <%= link_to 'Удалить', film_path(@film),
                  method: :delete,
                  data: { confirm: 'Вы хотите удалить этот фильм?' },
                  class: 'btn btn-sm btn-danger'
      %>
    <% end %>

    <table class="table film-info-table">
      <tbody>
      <tr>
        <td>Рейтинг</td>
        <td><%= @rating || @film.rating %></td>
      </tr>
      <tr>
        <td>Название</td>
        <td><%= @film.title %></td>
      </tr>
      <tr>
        <td>Год выпуска</td>
        <td><%= @film.year %></td>
      </tr>
      <tr>
        <td>Жанр</td>
        <td><%= @film.genre %></td>
      </tr>
      <tr>
        <td>Кинокомпания</td>
        <td><%= @film.company %></td>
      </tr>
      <tr>
        <td>Режиссер</td>
        <td><%= @film.producer %></td>
      </tr>
      <tr>
        <td>Актеры</td>
        <td><%= @film.actors %></td>
      </tr>
      <tr>
        <td>Стоимость</td>
        <td><%= @film.cost %></td>
      </tr>
      </tbody>
    </table>

    <% if current_user && !@rating %>
      <div class="submit-rating">
        <%= form_with(url: ratings_path, method: :post) do |form| %>
          <%= form.hidden_field :film_id, value: @film.id %>
          <%= form.hidden_field :user_id, value: current_user.id %>

          <div class="form-group">
            <%= form.label :value, 'Поставить рейтинг' %>
            <%= form.text_field :value, class: 'form-control rating-field' %>
          </div>

          <div class="actions">
            <%= form.submit 'Отправить', class: 'btn btn-sm btn-primary' %>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

<div class="film-comments">
  <h5>Комментарии</h5>

  <% if current_user %>
    <%= form_with(model: @film.comments, url: comments_path, method: :create) do |form| %>
      <%= form.hidden_field :film_id, value: @film.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>

      <div class="field mt-3">
        <%= form.label :text, 'Оставить комментарий:' %>
        <%= form.text_area :text, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Отправить', class: 'btn btn-sm btn-primary mt-3' %>
      </div>
    <% end %>
  <% end %>

  <% @comments.each do |comment| %>
    <div class="card comment">
      <p class="card-header"><%= comment.created_at %> – <%= comment.user.email %></p>
      <div class="card-body">
        <p class="card-text"><%= comment.text %></p>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Электронная видеотека</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Электронная видеотека <small class="badge kim-badge badge-secondary">by Kim Viktoria</small></a>
      <div>
        <% if user_signed_in? %>
          <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-danger login-btn' %>
        <% else %>
          <%= link_to 'Войти', new_user_session_path, class: 'btn btn-sm btn-primary login-btn' %>
          <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn btn-sm btn-success login-btn' %>
        <% end %>
      </div>
    </nav>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>